#!/usr/bin/env node
/**
 * Cuts the test fixture for docker/theme/tests out of a core's compiled UI:
 *
 *   node docker/theme/tests/fixtures/extract.mjs <core ui/dist> <out.mjs>
 *
 * It keeps every region theme.mjs reads (the Sidebar component whole, each
 * text rule's and anchor's match with a little context), the core's
 * declarations of every custom property theme.css overrides, and index.html.
 * Run it on the pristine core image's /app/ui/dist after a core bump (see
 * docs/theme.md, "After a core bump").
 */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { ANCHORS, SECTIONS } from "../../anchors.mjs";
import { TEXT_RULES } from "../../rules.mjs";

const THEME_DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const [dist, out] = process.argv.slice(2);
if (!dist || !out) {
  console.error("usage: extract.mjs <core ui/dist> <out.mjs>");
  process.exit(2);
}

const assets = path.join(dist, "assets");
const js = readdirSync(assets).filter((f) => f.endsWith(".js")).map((f) => readFileSync(path.join(assets, f), "utf8")).join("\n");

// Regions to keep, merged where they overlap.
const regions = [];
const keep = (start, end) => regions.push([Math.max(0, start), Math.min(js.length, end)]);
const first = SECTIONS[0];
const last = SECTIONS[SECTIONS.length - 1];
const sidebarStart = js.indexOf(first.start);
const sidebarEnd = js.indexOf(last.end, sidebarStart);
if (sidebarStart === -1 || sidebarEnd === -1) throw new Error("the Sidebar component was not found; check SECTIONS in anchors.mjs");
keep(sidebarStart - 40, sidebarEnd + last.end.length + 40);
for (const rule of TEXT_RULES.filter((r) => r.files.some((f) => f.includes("assets")))) {
  for (const match of js.matchAll(new RegExp(rule.pattern.source, "g"))) keep(match.index - 60, match.index + match[0].length + 60);
}
for (const anchor of ANCHORS.filter((a) => a.files.some((f) => f.includes("assets")))) {
  const at = js.indexOf(anchor.literal);
  if (at !== -1) keep(at - 40, at + anchor.literal.length + 40);
}
regions.sort((a, b) => a[0] - b[0]);
const merged = [];
for (const [start, end] of regions) {
  const previous = merged[merged.length - 1];
  if (previous && start <= previous[1]) previous[1] = Math.max(previous[1], end);
  else merged.push([start, end]);
}
const bundle = merged.map(([start, end]) => js.slice(start, end)).join(";\n");

const css = readdirSync(assets).filter((f) => f.endsWith(".css") && !f.startsWith("kyoube-")).map((f) => readFileSync(path.join(assets, f), "utf8")).join("\n");
const theme = readFileSync(path.join(THEME_DIR, "theme.css"), "utf8").replace(/\/\*[\s\S]*?\*\//g, "");
const tokens = [...new Set([...theme.matchAll(/(--[a-z0-9-]+)\s*:/g)].map((m) => m[1]).filter((name) => !name.startsWith("--kyoube-")))].sort();
const declarations = tokens.map((name) => new RegExp(`${name}:[^;}]*`).exec(css)?.[0]).filter(Boolean);
const html = readFileSync(path.join(dist, "index.html"), "utf8");

writeFileSync(out, `/**
 * Excerpts of a core's compiled UI, used by theme.spec.mjs. Generated by
 * extract.mjs (${merged.length} regions, ${declarations.length}/${tokens.length} token declarations); regenerate rather than edit.
 * BUNDLE: every region docker/theme reads, joined with ";". CORE_CSS: the
 * core's declarations of the custom properties theme.css overrides.
 * INDEX_HTML: ui/dist/index.html.
 */
export const BUNDLE = ${JSON.stringify(bundle)};

export const CORE_CSS = ${JSON.stringify(`:root{${declarations.join(";")}}`)};

export const INDEX_HTML = ${JSON.stringify(html)};
`);
console.log(`wrote ${out}: ${merged.length} regions, ${bundle.length} characters, ${declarations.length}/${tokens.length} tokens`);
